Implement registration checking

diff --git a/flag-parsing-internal/flag-parsing-internal b/flag-parsing-internal/flag-parsing-internal
--- a/flag-parsing-internal/flag-parsing-internal
+++ b/flag-parsing-internal/flag-parsing-internal
@@ -18,6 +18,10 @@ declare -ag POS_ORDER
 declare -Ag ARG_VALUES
 declare -Ag OPT_COUNTS
 
+declare -Ag ARGS
+declare -ag REGISTRATIONS
+declare -ag REG_ERRORS
+
 
 ###############################################################################
 # Main: main functions to control parsing
@@ -25,6 +29,20 @@ declare -Ag OPT_COUNTS
 parse() {
   local -n OUTPUT="$1" ; shift 1
   local -a POS_RAW
+
+  local has_err='false'
+  for i in "${!REG_ERRORS[@]}"; do
+    local reg="${REGISTRATIONS[i]}"
+    local err="${REG_ERRORS[i]}"
+    if [[ ! -z "${err}" ]]; then
+      printf '%s. %s\n' "${i}" "${reg}" >&2
+      printf '%s\n\n' "${err}" >&2
+      has_err='true'
+    fi
+  done
+  if $has_err; then
+    return 1
+  fi
 
   while (( "$#" )); do 
     # Registered options
@@ -75,6 +93,18 @@ parse() {
 #               for the parser
 ###############################################################################
 
+register_base() {
+  local -r name="$1"
+  local -r opts="$2"
+
+  REGISTRATIONS+=("${name:-<no name>} ${opts}")
+  REG_ERRORS+=('')
+
+  check_base "${name}" || return 1
+
+  ARGS["${name}"]='true'
+}
+
 register_opt_base() {
   local -r name="$1"
   local -r opts="$2"
@@ -85,6 +115,9 @@ register_opt_base() {
   local -r instances="${7:-0}"
   local -r action="${8:-store}"
 
+  register_base "${name}" "${opts}" || return 1
+  check_opt_base "${name}" "${opts}" || return 1
+
   OPTS["${name}"]="${opts}"
   NUM_OPT_ARGS["${name}"]="${num_args}"
   REQUIRED["${name}"]="${required}"
@@ -92,6 +125,7 @@ register_opt_base() {
   STORE["${name}"]="${store}"
   INSTANCES["${name}"]="${instances}"
   ACTION["${name}"]="${action}"
+  POST_PARSE["${name}"]=''
 
   ARG_VALUES["${name}"]=''
   OPT_COUNTS["${name}"]=0
@@ -103,12 +137,20 @@ register_opt_from_dict() {
   local -n _options="$3"
 
   # Basic registration
-  register_opt_base "${name}" "${opts}"
+  register_opt_base "${name}" "${opts}" || return 1
   
-  # Apply option overrides
+  # Apply setting overrides
   for option in "${!_options[@]}"; do
     local option_val="${_options[${option}]}"
+
+    # Check for registration errors
+    check_opt_from_dict "${option}" "${option_val}" || return 1
+
+    # Set to global
     printf -v "${option}"["${name}"] "${option_val}"
+
+    # Add setting to registration record
+    REGISTRATIONS[-1]="${REGISTRATIONS[-1]} [${option}]=${option_val}"
   done
 }
 
@@ -119,14 +161,6 @@ register_opt_from_line() {
 
   eval local -A options=( "${option_str}" )
   register_opt_from_dict "${name}" "${opts}" options
-}
-
-register_opt_value() {
-  local -r name="$1"
-  local -n attr="$2"
-  local -r val="$3"
-
-  attr["${name}"]="${val}"
 }
 
 register_opt_bool() {
@@ -162,6 +196,9 @@ register_pos() {
   local -r required="${3:-'true'}"
   local -r default="${4}"
 
+  register_base "${name}" || return 1
+  check_pos "${name}" || return 1
+
   NUM_POS_ARGS["${name}"]="${num_args}"
   REQUIRED["${name}"]="${required}"
   DEFAULT["${name}"]="${default}"
@@ -170,14 +207,91 @@ register_pos() {
   ARG_VALUES["${name}"]=''
 }
 
+register_err() {
+  local -r msg="$1"
+  local -r usage="$2"
+  if [[ -z "${REG_ERRORS[-1]}" ]]; then
+    REG_ERRORS[-1]="${usage}"
+  fi
+  REG_ERRORS[-1]="${REG_ERRORS[-1]}
+$(echo ${msg} | indent)"
+}
+
 
 ###############################################################################
 # Checking: functions to check the registered args before we start parsing
 ###############################################################################
 
-# empty, sad :(
+check_base() {
+  local -r name="$1"
 
+  if [[ -z "${name}" ]]; then
+    register_err \
+      "register_base: Missing required field 'name'" \
+      "$(usage_register_base)"
+     return 1
+  fi
 
+  if [[ -v ARGS["${name}"] ]] ; then
+    register_err \
+      "register_base: '${name}' is already registered" \
+      "$(usage_register_base)"
+    return 1
+  fi
+}
+
+check_opt_base() {
+  local -r name="$1"
+  local -r opts="$2"
+
+  if [[ -z "${opts}" ]]; then
+    register_err \
+      "register_opt_base: Missing required field 'opts'" \
+      "$(usage_register_opt_base)"
+  fi
+
+   for flag in "${!OPTS[@]}"; do
+    if [[ "${opts}" == "${OPTS[${flag}]}" ]]; then
+      register_err \
+        "register_opt_base: a flag with options '${opts}' is already defined" \
+        "$(usage_register_opt_base)"
+      return 1
+    fi
+  done
+}
+
+check_opt_from_dict() {
+  local -r option="$1"
+  local -r option_val="$2"
+  
+  set | grep "^${option}=" >/dev/null
+  local is_defined="$?"
+
+  if (( is_defined != 0 )); then
+    register_err \
+      "register_opt_from_dict: '${option}' is not a valid flag setting" \
+      "$(usage_register_opt_from_dict)"
+    return 1
+  fi
+
+  if [[ -z "${option_val}" ]]; then
+    register_err \
+      "register_opt_from_dict: '${option}' requires a setting value" \
+      "$(usage_register_opt_from_dict)"
+    return 1
+  fi
+}
+
+check_pos() {
+  local -r name="$1"
+
+  if [[ -z "${name}" ]]; then
+    register_err \
+      "register_pos: Missing required field 'name'" \
+      "$(usage_register_pos)"
+    return 1
+  fi
+}
 
 ###############################################################################
 # Processing: consume registered args from the stream of input
@@ -311,7 +425,9 @@ post_parse() {
     local callback="${POST_PARSE[${flag}]}"
     local opts="${OPTS[${flag}]:-'--'}"
     local val="${ARG_VALUES[${flag}]}"
-    "${callback}" "${flag}" "${opts}" "${val}"
+    if [[ ! -z "${callback}" ]]; then
+      "${callback}" "${flag}" "${opts}" "${val}"
+    fi
   done
 }
 
@@ -372,6 +488,44 @@ unsupported_action() {
   printf '%s\n' "Error: '${_name}' was called with an unsupported action: ${_action}" >&2
 }
 
+registration_errors() {
+  printf '%s\n' '!!! Errors encountered registering args'
+}
+
+
+###############################################################################
+# Usage: functions to print usage for API functions
+###############################################################################
+
+usage_register_base() {
+  printf '%s\n%s\n' \
+    'Usage: register_base name [opts]' \
+    'Registers an argument to be parsed from the command line'
+}
+
+usage_register_opt_base() {
+  printf '%s%s\n%s\n' 'Usage: register_opt_base name opts [num_args] ' \
+    '[required] [default] [store] [instances] [action]' \
+    'Registers an optional argument to be parsed from the command line'
+}
+
+usage_register_opt_from_dict() {
+  printf '%s\n%s' 'Usage: register_opt_from_dict name opts [settings]' \
+    'Registers an optional command line argument using provided settings'
+}
+
+usage_register_pos() {
+  printf '%s\n' \
+    'Usage: register_pos name [num_args] [required] [default]' \
+    'Registers a positional argument, where:' \
+    'num_args: number of positional arguments collected into
+          the argument. -1 indicates 0 or more' \
+    'required: if true, enough positional arguments must be 
+          provided to fill this argument' \
+    'default:  value to use if no positional arguments are
+          consumed for this argument'
+}
+
 
 ###############################################################################
 # Utils
@@ -395,6 +549,10 @@ print_all() {
 
 print_arg() {
   printf '%s\n%s\n' 'Printing an arg!' "$@"
+}
+
+indent() {
+  sed 's/^/  /'
 }
 
 copy_array() {
