Re-organize flag-parsing sections

diff --git a/flag-parsing-internal/flag-parsing-internal b/flag-parsing-internal/flag-parsing-internal
--- a/flag-parsing-internal/flag-parsing-internal
+++ b/flag-parsing-internal/flag-parsing-internal
@@ -1,99 +1,80 @@
 #!/bin/bash
 
-## Tools
-debug() {
-  local -n arr="$1"
-  printf '\n%s\n' "DEBUG: ${!arr}"
-  for flag in "${!arr[@]}"; do
-    printf ' [%s]=%s\n' "${flag}" "${arr[${flag}]}"
+##############################################################################
+# Declarations: Globals that hold the parser state
+#               including registration and parsed values
+##############################################################################
+declare -Ag OPTS
+declare -Ag NUM_OPT_ARGS
+declare -Ag NUM_POS_ARGS
+declare -Ag REQUIRED
+declare -Ag DEFAULTS
+declare -Ag ACTIONS
+declare -Ag STORE
+declare -Ag INSTANCES
+declare -Ag POST_PARSE
+declare -ag POS_ORDER
+
+declare -Ag ARG_VALUES
+declare -Ag OPT_COUNTS
+
+
+###############################################################################
+# Main: main functions to control parsing
+###############################################################################
+parse() {
+  local -n OUTPUT="$1" ; shift 1
+  local -a POS_RAW
+
+  while (( "$#" )); do 
+    # Registered options
+    for flag in "${!OPTS[@]}"; do
+      local opts="${OPTS[${flag}]}"
+      local num_args="${NUM_OPT_ARGS[${flag}]}"
+ 
+      local regex="^(${opts})$"
+      if [[ "$1" =~ $regex ]]; then
+        consume_flag "${flag}" "$@" || return 1
+        shift $(( num_args + 1 ))
+        continue 2
+      fi
+    done
+    
+    # Default options
+    case "$1" in
+      -h|--help)
+        usage
+        exit 0
+        ;;
+      --) # End argument parsing
+        shift
+        POS_RAW+=("$@")
+        break
+        ;;
+      -*|--*=) # unsupported flags
+        echo "Error: Unsupported flag $1" >&2
+        return 1
+        ;;
+      *) # preserve positional arguments
+        POS_RAW+=("$1")
+        shift
+        ;;
+    esac
   done
-}
+  
+  consume_pos "${POS_RAW[@]}" || return 1
+  validate_opts || return 1
+  post_parse
 
-print_all() {
-  echo
-  echo "Args:"
-  for flag in "${!ARG_VALUES[@]}"; do
-    printf ' [%s]=%s\n' "${flag}" "${ARG_VALUES[${flag}]}"
-  done
-}
-
-print_arg() {
-  printf '%s\n%s\n' 'Printing an arg!' "$@"
-}
-
-copy_array() {
-  local -n in="$1"
-  local -n out="$2"
-
-  # Clear existing out array
-  for key in "${!out[@]}"; do
-    unset out["${key}"]
-  done
-
-  # Copy each key-value pair from in to out
-  for key in "${!in[@]}"; do 
-    local val="${in[${key}]}"
-    out["${key}"]="${val}"
-  done
+  copy_array ARG_VALUES OUTPUT
 }
 
 
-## Flag parsing
+###############################################################################
+# Registration: functions to register optional and positional arguments
+#               for the parser
+###############################################################################
 
-# Err messages
-missing_args() {
-  local -r _name="$1"
-  local -r _req="$2"
-  local -r _prov="$3"
-  printf '%s\n%s\n' \
-    "Error: '${_name}' has required arguments: ${_req}" \
-    "Provided: ${_prov}" \
-    >&2
-}
-
-missing_required() {
-  local -r _name="$1"
-  printf '%s\n' "Error: missing required option: ${_name}" >&2
-}
-
-too_many_instances() {
-  local -r _name="$1"
-  local -r _count="$2"
-  local -r _max="$3"
-  printf '%s\n%s\n%s\n' \
-    "Error: '${_name}' has too many instances." \
-    "Given: ${_count}" \
-    "Max: ${_max}" \
-    >&2
-}
-
-missing_pos_args() {
-  local -r _name="$1"
-  local -r _num="$2"
-  local -r _actual="$3"
-  printf '%s\n%s\n%s\n' \
-    "Error: '${_name}' is missing positional arguments." \
-    "Given: ${_actual}" \
-    "Required: ${_num}" \
-    >&2
-}
-
-too_many_pos_args() {
-  printf 'Error: too many positional arguments provided\n' >&2
-}
-
-missing_required_pos() {
-  local -r _name="$1"
-  printf '%s\n' "Error: missing required positional argument '${_name}'" >&2
-}
-
-unsupported_action() {
-  local -r _name="$1"
-  local -r _action="$2"
-  printf '%s\n' "Error: '${_name}' was called with an unsupported action: ${_action}" >&2
-}
-
-# Registration
 register_opt() {
   local -r name="$1"
   local -r opts="$2"
@@ -139,7 +120,18 @@ register_pos() {
 }
 
 
-# Processing
+###############################################################################
+# Checking: functions to check the registered args before we start parsing
+###############################################################################
+
+# empty, sad :(
+
+
+
+###############################################################################
+# Processing: consume registered args from the stream of input
+###############################################################################
+
 consume_flag() {
   local -r name="$1" ; shift 2
   
@@ -221,7 +213,10 @@ consume_pos() {
 }
 
 
-# Validation
+###############################################################################
+# Validation: functions to validate the parsed args
+###############################################################################
+
 validate_opts() {
   # Required
   for flag in "${!REQUIRED[@]}"; do
@@ -254,7 +249,11 @@ validate_opts() {
 }
 
 
-# Post parse
+
+###############################################################################
+# Post-parsing: execute callbacks for each argument
+###############################################################################
+
 post_parse() {
   # Post parse funcs
   for flag in "${!POST_PARSE[@]}"; do
@@ -266,66 +265,100 @@ post_parse() {
 }
 
 
-# Main
-parse() {
-  local -n OUTPUT="$1" ; shift 1
-  local -a POS_RAW
+###############################################################################
+# Error messages: print custom errors to stdout
+###############################################################################
 
-  while (( "$#" )); do 
-    # Registered options
-    for flag in "${!OPTS[@]}"; do
-      local opts="${OPTS[${flag}]}"
-      local num_args="${NUM_OPT_ARGS[${flag}]}"
- 
-      local regex="^(${opts})$"
-      if [[ "$1" =~ $regex ]]; then
-        consume_flag "${flag}" "$@" || return 1
-        shift $(( num_args + 1 ))
-        continue 2
-      fi
-    done
-    
-    # Default options
-    case "$1" in
-      -h|--help)
-        usage
-        exit 0
-        ;;
-      --) # End argument parsing
-        shift
-        POS_RAW+=("$@")
-        break
-        ;;
-      -*|--*=) # unsupported flags
-        echo "Error: Unsupported flag $1" >&2
-        return 1
-        ;;
-      *) # preserve positional arguments
-        POS_RAW+=("$1")
-        shift
-        ;;
-    esac
-  done
-  
-  consume_pos "${POS_RAW[@]}" || return 1
-  validate_opts || return 1
-  post_parse
-
-  copy_array ARG_VALUES OUTPUT
+missing_args() {
+  local -r _name="$1"
+  local -r _req="$2"
+  local -r _prov="$3"
+  printf '%s\n%s\n' \
+    "Error: '${_name}' has required arguments: ${_req}" \
+    "Provided: ${_prov}" \
+    >&2
 }
 
-# Declarations
-declare -Ag OPTS
-declare -Ag NUM_OPT_ARGS
-declare -Ag NUM_POS_ARGS
-declare -Ag REQUIRED
-declare -Ag DEFAULTS
-declare -Ag ACTIONS
-declare -Ag STORE
-declare -Ag INSTANCES
-declare -Ag POST_PARSE
-declare -ag POS_ORDER
+missing_required() {
+  local -r _name="$1"
+  printf '%s\n' "Error: missing required option: ${_name}" >&2
+}
 
-declare -Ag ARG_VALUES
-declare -Ag OPT_COUNTS
+too_many_instances() {
+  local -r _name="$1"
+  local -r _count="$2"
+  local -r _max="$3"
+  printf '%s\n%s\n%s\n' \
+    "Error: '${_name}' has too many instances." \
+    "Given: ${_count}" \
+    "Max: ${_max}" \
+    >&2
+}
+
+missing_pos_args() {
+  local -r _name="$1"
+  local -r _num="$2"
+  local -r _actual="$3"
+  printf '%s\n%s\n%s\n' \
+    "Error: '${_name}' is missing positional arguments." \
+    "Given: ${_actual}" \
+    "Required: ${_num}" \
+    >&2
+}
+
+too_many_pos_args() {
+  printf 'Error: too many positional arguments provided\n' >&2
+}
+
+missing_required_pos() {
+  local -r _name="$1"
+  printf '%s\n' "Error: missing required positional argument '${_name}'" >&2
+}
+
+unsupported_action() {
+  local -r _name="$1"
+  local -r _action="$2"
+  printf '%s\n' "Error: '${_name}' was called with an unsupported action: ${_action}" >&2
+}
+
+
+###############################################################################
+# Utils
+###############################################################################
+
+debug() {
+  local -n arr="$1"
+  printf '\n%s\n' "DEBUG: ${!arr}"
+  for flag in "${!arr[@]}"; do
+    printf ' [%s]=%s\n' "${flag}" "${arr[${flag}]}"
+  done
+}
+
+print_all() {
+  echo
+  echo "Args:"
+  for flag in "${!ARG_VALUES[@]}"; do
+    printf ' [%s]=%s\n' "${flag}" "${ARG_VALUES[${flag}]}"
+  done
+}
+
+print_arg() {
+  printf '%s\n%s\n' 'Printing an arg!' "$@"
+}
+
+copy_array() {
+  local -n in="$1"
+  local -n out="$2"
+
+  # Clear existing out array
+  for key in "${!out[@]}"; do
+    unset out["${key}"]
+  done
+
+  # Copy each key-value pair from in to out
+  for key in "${!in[@]}"; do
+    local val="${in[${key}]}"
+    out["${key}"]="${val}"
+  done
+}
 
